-- Generated by scripts/hypr2lua.
-- Source: /home/oldjobobo/Projects/themes/omarchy-event-horizon-theme/hyprland.conf

local activeBorderColor = {
  colors = {
    "rgba(e95678ff)",  -- color1, rosa/rojo
    "rgba(ee64acff)",  -- color5, magenta
    "rgba(26bbd9ff)",  -- accent, cyan/azul
    "rgba(59e3e3ff)",  -- color6, cyan claro
    "rgba(29d398ff)",  -- color2, verde agua
    "rgba(fab795ff)",  -- color3, naranja
    "rgba(e95678ff)",  -- cierra el loop en el mismo color inicial
  },
  angle = 45,
}

local inactiveBorderColor = "rgba(1c1e2666)"  -- background con alpha, apagado

hl.config({
	general = {
    	col = {
      	active_border = activeBorderColor,
      	inactive_border = inactiveBorderColor,
    	},
    	border_size = 2,
    	gaps_in = 2,
    	gaps_out = 8,
  		},
	group = {
		col = {
			border_active = activeBorderColor,
			border_inactive = inactiveBorderColor,
		},
	},
	decoration = {
		rounding = 4,
		rounding_power = 3,
		active_opacity = 1,
		inactive_opacity = 0.99,
		
		blur = {
			enabled = true,
			size = 2,
			passes = 1,
			noise = 0.01,
			contrast = 1,
			brightness = 0.3,
			vibrancy = 0.03,
			vibrancy_darkness = 0.70,
			ignore_opacity = false,
			new_optimizations = true,
		},
		
		shadow = {
			enabled = true,
			scale = 2.0,
			range = 24,
			render_power = 4,
		},
	},
	animations = {
		enabled = true,
	},
})

hl.curve("smoothFlow", { type = "bezier", points = { { 0.25, 0.46 }, { 0.45, 0.94 } } })
hl.curve("liquidSnap", { type = "bezier", points = { { 0.68, -0.55 }, { 0.265, 1.55 } } })
hl.curve("appleSilk", { type = "bezier", points = { { 0.34, 1.56 }, { 0.64, 1 } } })
hl.curve("elasticPop", { type = "bezier", points = { { 0.175, 0.885 }, { 0.32, 1.275 } } })

hl.animation({
	leaf = "windows",
	enabled = true,
	speed = 2.0,
	bezier = "smoothFlow",
	style = "slide",
})
hl.animation({
	leaf = "windowsOut",
	enabled = true,
	speed = 2.0,
	bezier = "smoothFlow",
	style = "popin 80%",
})
hl.animation({
	leaf = "windowsIn",
	enabled = true,
	speed = 2.0,
	bezier = "smoothFlow",
	style = "slide",
})
hl.animation({
	leaf = "border",
	enabled = true,
	speed = 2.5,
	bezier = "smoothFlow",
})
hl.animation({
	leaf = "workspaces",
	enabled = true,
	speed = 2.2,
	bezier = "smoothFlow",
	style = "slidevert",
})
hl.animation({
	leaf = "fade",
	enabled = true,
	speed = 1.5,
	bezier = "smoothFlow",
})
hl.animation({
	leaf = "layers",
	enabled = true,
	speed = 2,
	bezier = "elasticPop",
})